export const defaultData = {
  email: {
    Description: "Issue",
    Detailed_Decription: "Descripe",
    Impact: "3-Moderate/Limited",
    Urgency: "3-Medium",
    Status: "Assigned",
    "Reported Source": "Phone",
    Service_Type: "User Service Request",
    z1D_Action: "CREATE",
    "Categorization Tier 1": "Systems",
    "Categorization Tier 2": "Email",
  },
  network: {
    Description: "Issue",
    Detailed_Decription: "Descripe",
    Impact: "3-Moderate/Limited",
    Urgency: "3-Medium",
    Status: "Assigned",
    "Reported Source": "Phone",
    Service_Type: "User Service Request",
    z1D_Action: "CREATE",
    "Categorization Tier 1": "Network",
    "Categorization Tier 2": "Wi-fi",
  },
  useraccount: {
    Description: "Issue",
    Detailed_Decription: "Descripe",
    Impact: "3-Moderate/Limited",
    Urgency: "3-Medium",
    Status: "Assigned",
    "Reported Source": "Phone",
    Service_Type: "User Service Request",
    z1D_Action: "CREATE",
    "Categorization Tier 1": "Software",
    "Categorization Tier 2": "User Account",
  },
  computer: {
    Description: "Issue",
    Detailed_Decription: "Descripe",
    Impact: "3-Moderate/Limited",
    Urgency: "3-Medium",
    Status: "Assigned",
    "Reported Source": "Phone",
    Service_Type: "User Service Request",
    z1D_Action: "CREATE",
    "Categorization Tier 1": "Hardware",
    "Categorization Tier 2": "PC",
  },
  printer: {
    Description: "Issue",
    Detailed_Decription: "Descripe",
    Impact: "3-Moderate/Limited",
    Urgency: "3-Medium",
    Status: "Assigned",
    "Reported Source": "Phone",
    Service_Type: "User Service Request",
    z1D_Action: "CREATE",
    "Categorization Tier 1": "Hardware",
    "Categorization Tier 2": "PC",
  },
};
